---

ansible_python_interpreter: auto_silent

executor_user: gitlab-executor

update_homebrew: true

# Software versions

ginkgo_version: "1.15.2"
golang_version: "1.16"
golangci_lint_version: "1.46.2"
gomega_version: "1.11.0"
go_junit_report_version: "0.9.1"
jq_version: "jq-1.5"
yq_version: "3.4.1"

gitlab_runner_version: "15.1.0"
# See https://gitlab-runner-downloads.s3.amazonaws.com/v{{ gitlab_runner_version }}/index.html
gitlab_runner_hash: 96862945d4d1b5f9c16f36ffcf00630a23f49fbddda5dce91ecc29c4077729fd
