---

- name: Copy job-variables script
  become: true
  template:
    src: setup-job-variables.sh
    dest: /Users/{{ executor_user }}/bin/setup-job-variables.sh
    owner: "{{ executor_user }}"
    group: "{{ executor_user }}"
    mode: 'u=r,g=,o='

- name: Retrieve expanded job-variables script
  become: true
  fetch:
    src: /Users/{{ executor_user }}/bin/setup-job-variables.sh
    dest: ../build
  when: fetch_files
