---

- name: Copy pre-build script
  become: true
  template:
    src: pre-build.sh
    dest: /Users/{{ executor_user }}/bin/pre-build.sh
    owner: "{{ executor_user }}"
    group: "{{ executor_user }}"
    mode: 'u=r,g=,o='

- name: Retrieve expanded pre-build script
  become: true
  fetch:
    src: /Users/{{ executor_user }}/bin/pre-build.sh
    dest: ../build
  when: fetch_files
