---

- name: Set per-user keychain variables
  set_fact:
    per_user_keychain_script: /Users/{{ executor_user }}/bin/setup-keychain.sh
    per_user_keychain_sentinel: /Users/{{ executor_user }}/.setup-keychain-success
    per_user_keychain_dump: /Users/{{ executor_user }}/{{ keychain_name }}.txt

- name: Copy pre-clone script
  become: true
  template:
    src: pre-clone.sh
    dest: /Users/{{ executor_user }}/bin/pre-clone.sh
    owner: "{{ executor_user }}"
    group: "{{ executor_user }}"
    mode: 'u=rx,g=,o='

- name: Retrieve expanded pre-clone script
  become: true
  fetch:
    src: /Users/{{ executor_user }}/bin/pre-clone.sh
    dest: ../build
  when: fetch_files

- name: Copy setup-keychain script
  become: true
  template:
    src: setup-keychain.sh
    dest: "{{ per_user_keychain_script }}"
    owner: "{{ executor_user }}"
    group: "{{ executor_user }}"
    mode: 'u=rx,g=,o='
  notify: clean-user-keychain-files

- name: Retrieve expanded setup-keychain script
  become: true
  fetch:
    src: "{{ per_user_keychain_script }}"
    dest: ../build
  when: fetch_files

# 'login' doesn't reliably propagate status codes from the command it invokes, so we work around this by
# having the install script create a sentinel file when it succeeds.
- name: Run setup-keychain script
  become: true
  command:
    argv:
      - login
      - -f
      - "{{ executor_user }}"
      - "{{ per_user_keychain_script }}"
  register: setup_keychain

- name: Setup-keychain script output
  debug:
    msg: "setup_keychain.stdout = {{ setup_keychain.stdout }}"

- name: Setup-keychain script stderr
  debug:
    msg: "setup_keychain.stderr = {{ setup_keychain.stderr }}"
  when: debug_provisioning and setup_keychain.stderr != ""

- name: Retrieve keychain
  become: true
  fetch:
    src: "{{ keychain_path }}"
    dest: ../build
  when: fetch_files
  ignore_errors: true

- name: Retrieve keychain dump
  become: true
  fetch:
    src: "{{ per_user_keychain_dump }}"
    dest: ../build
  when: fetch_files
  ignore_errors: true

# - pause:
#     minutes: 60
#   when: debug_provisioning

- name: Check if keychain setup succeeded
  become: true
  stat:
    path: "{{ per_user_keychain_sentinel }}"
  register: keychain_sentinel_file

- name: Fail the play if keychain setup failed.
  fail:
    msg: "{{ setup_keychain.stderr }}"
  when: not keychain_sentinel_file.stat.exists
