---

- become: true
  block:
    - name: Gitlab executor group
      group:
        name: "{{ executor_user }}"

    - name: Gitlab executor user
      user:
        name: "{{ executor_user }}"
        password: "{{ executor_password | trim }}"
        comment: GitLab Executor
        groups:
          - "{{ executor_user }}"
          - _developer
          - com.apple.access_ssh
        hidden: true
        shell: /bin/bash

    - name: Gitlab executor directories
      file:
        path: /Users/{{ executor_user }}/{{ item }}
        state: directory
        owner: "{{ executor_user }}"
        group: "{{ executor_user }}"
        mode: 'u=rwx,g=,o='
      loop:
        - .ssh
        - bin
        - builds
        - caches
        - go
        - go/bin

    - name: Create bash profile
      template:
        src: .bash_profile
        dest: /Users/{{ executor_user }}/.bash_profile
        owner: "{{ executor_user }}"
        group: "{{ executor_user }}"
        mode: 'u=r,g=,o='

    - name: Copy scripts
      template:
        src: "{{ item }}.sh"
        dest: /Users/{{ executor_user }}/bin/{{ item }}.sh
        owner: "{{ executor_user }}"
        group: "{{ executor_user }}"
        mode: 'u=rx,g=,o='
      loop:
        - get-golang-packages

    - name: Install per-user golang packages
      command:
        argv:
          - login
          - -f
          - "{{ executor_user }}"
          - /Users/{{ executor_user }}/bin/get-golang-packages.sh
      register: run_user_golang_packages

    - name: Display per-user golang log
      debug:
        msg: "{{ run_user_golang_packages.stdout }}"
      when: run_user_golang_packages.stdout != ""

    - name: Display per-user golang error log
      debug:
        msg: "{{ run_user_golang_packages.stderr }}"
      when: run_user_golang_packages.stderr != ""
