---

all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: auto_silent

      keychain_certificates:
{% for item in keychain_certificates %}
        - file: {{ item.file }}
          password: {{ item.password | trim }}
{% endfor %}

      apple_credentials:
        user: {{ apple_developer_program_credentials.user }}
        password: {{ apple_developer_program_credentials.password | trim }}
        provider: {{ apple_developer_program_credentials.provider | trim }}
