---

- name: Provision Per-User Resources
  hosts: all
  gather_facts: false
  tasks:
    - name: Setup custom keychain
      block:
        - name: Create keychain
          command:
            argv:
              - security
              - create-keychain
              - -p
              - "{{ keychain_password | trim }}"
              - executor

        - name: Unlock keychain
          command:
            argv:
              - security
              - unlock-keychain
              - -p
              - "{{ keychain_password | trim }}"
              - executor

        - name: Set keychain settings
          command:
            argv:
              - security
              - set-keychain-settings
              - -u
              - executor

        - name: Import certificates
          command:
            argv:
              - security
              - import
              - ~/.temp/{{ '{{' }} item.file {{ '}}' }}
              - -f
              - pkcs12
              - -k
              - executor
              # The '-A' option allows any application to read keys.
              # This would be insecure if the keychain was retained but Gitlab executor VMs are thrown away after use.
              - -A
              - -T
              - /usr/bin/codesign
              - -T
              - /usr/bin/security
              - -P
              - "{{ '{{' }} item.password {{ '}}' }}"
          loop: "{{ '{{' }} keychain_certificates {{ '}}' }}"
          loop_control:
            label: "{{ '{{' }} item.file {{ '}}' }}"

        - name: Allow Apple tools to access signing keys
          command:
            argv:
              - security
              - set-key-partition-list
              - -S
              - "apple-tool:,apple:,codesign:"
              - -k
              - "{{ keychain_password | trim }}"
              - executor

        - name: Add keychain to search list
          command:
            argv:
              - security
              - list-keychains
              - -d
              - user
              - -s
              - executor

    - name: Install golang packages
      command: go get {{ '{{' }} item {{ '}}' }}
      loop:
        - github.com/onsi/ginkgo/ginkgo@v{{ ginkgo_version }}
        - github.com/onsi/gomega/...@v{{ gomega_version }}
        - github.com/jstemmer/go-junit-report@v{{ go_junit_report_version }}
