---

- name: Provision Ticksmith Gitlab Executor VM
  hosts: default
  tasks:
    - name: Disable sleep
      import_tasks: tasks/no-sleep.yaml

    - name: Install software
      import_tasks: tasks/software.yaml

    - name: Setup executor user
      import_tasks: tasks/user.yaml

  handlers:
    - name: Clean up golangci-lint installation script
      file:
        dest: /tmp/install-golangci-lint.sh
        state: absent
      listen: clean-golangci-lint-install

    - name: Clean up gitlab-executor temp directory
      become: true
      file:
        dest: /Users/{{ user_name }}/.temp/
        state: absent
      listen: clean-executor-temp-dir
